pipe = Popen(['mpv', urls, '--force-window'] + 
input-ipc-server=/tmp/mpvsocket
--auto-window-resize=no
--no-keepaspect-window

--no-osc
#--no-osd-bar
--osd-level=1

--osd-font='Ubuntu Sans Mono'
--osd-font-size=22.25

--osd-on-seek=msg
loop-file='inf'

mute=yes

screenshot-directory="~/Pictures/mpvscreenshots"
screenshot-template="%F-%P"
