#! /bin/sh

###Modified by nnasa

### AUTO_START ###

/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# picom --experimental-backends &
# feh --bg-fill Pictures/Wallpaper/SCANDAL-crate.jpg
$HOME/.config/polybar/launch.sh &
nm-applet &
pgrep -x sxhkd > /dev/null || sxhkd &
# mpd &


### MONITORS ###
bspc wm -O HDMI-1 DP-2
bspc monitor HDMI-1 -d 1 2 3 4
bspc monitor DP-2 -d 5 6 7 8

### BSPWM configuration ###
bspc config top_padding		-5
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config border_width	3
bspc config window_gap		5

# bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
# bspc config focus_follows_pointer true

############

### DWM Master-Stack layout ###
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

# how much of the screen the "master" takes by default
bspc config split_ratio 0.6

##############

### BSPWM coloring ###

bspc config normal_border_color		"#5e81ac" #bluegray
bspc config active_border_color		"#ffffff" #white
bspc config focused_border_color	"#A9AC00" #yellowishgreen
bspc config presel_feedback_color	"#5e81ac" #bluegray
bspc config urgent_border_color		"#dd2727" #red

### Apps rules ###
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a Spotify desktop='^3'
# bspc rule -a Alacritty:Ncmpcpp desktop='^3'
bspc rule -a *:Ncmpcpp follow=on desktop='^3' state=tiled
# bspc rule -a firefox desktop='^5'
bspc rule -a opera desktop='^5'

bspc rule -a Gcolor2 state=tiled
# bspc rule -a mplayer2 state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
