[main]
font=Ubuntu Sans Mono:weight=Regular:size=6.75
# use-bold=yes
anchor=top
#y-margin=30
width=50
lines=10
layer=overlay

horizontal-pad=15
vertical-pad=15
inner-pad=5

# hide-prompt=true

[colors]
# Dracula Theme Example
background=242424ff
text=afafafff
selection=6089a8ff
selection-text=242424ff
border=6089a8ff
match=c4a841ff
selection-match=afafafff

[border]
width=5
radius=15
