font=Ubuntu Sans Mono:size=13.5
# Symbols Nerd Font Mono:size=11.25
# dpi-aware=yes
pad=0x0
term=xterm-256color

[bell]
urgent=yes

[cursor]
style=block
blink=yes

[colors-dark]
alpha=0.85  # Transparency must be less than 1.0
blur=yes   # Enables the blur effect
cursor= 2a2a2a 757575
foreground=B0B0B0
background=1a1a1a

regular0=3B4252 # black
regular1=BF616A	# red
regular2=6CCD64	# green
regular3=C4A841	# yellow
regular4=6089A8	# blue
regular5=B48EAD # magenta
regular6=88C0D0	# cyan
regular7=DFDFDF	# white

bright0=4C566A
bright1=BF616A
bright2=6CCD64
bright3=C4A841
bright4=6089A8
bright5=B48EAD
bright6=8FBCBB
bright7=BDC3C7
